export type Brightness = 'light' | 'dark';
export type BlurStyleType = 'inner' | 'normal' | 'outer' | 'solid';
export type TextThemeKey =
  | 'bodyLarge'
  | 'bodyMedium'
  | 'bodySmall'
  | 'displayLarge'
  | 'displayMedium'
  | 'displaySmall'
  | 'headlineLarge'
  | 'headlineMedium'
  | 'headlineSmall'
  | 'labelLarge'
  | 'labelMedium'
  | 'labelSmall'
  | 'titleLarge'
  | 'titleMedium'
  | 'titleSmall';

type TextStyleKey =
  | 'color'
  | 'backgroundColor'
  | 'fontSize'
  | 'fontWeight'
  | 'fontStyle'
  | 'letterSpacing'
  | 'wordSpacing'
  | 'textBaseline'
  | 'height'
  | 'foreground'
  | 'background'
  | 'shadows'
  | 'fontFeatures'
  | 'decoration'
  | 'decorationColor'
  | 'decorationStyle'
  | 'decorationThickness'
  | 'debugLabel'
  | 'locale'
  | 'family'
  | 'package';

export type TextThemeValue = {
  [K in TextThemeKey as `textTheme.${K}`]: K;
};

type TextThemeWithStyle = {
  [K in TextThemeKey]: {
    [S in TextStyleKey]: `#theme.textTheme.${K}.${S}`;
  };
};

export type CombineTextThemeWithTextStyle = {
  [K in keyof TextThemeWithStyle]: TextThemeWithStyle[K][TextStyleKey];
}[keyof TextThemeWithStyle];

export type GoogleFontName =
  | 'Roboto'
  | 'OpenSans'
  | 'Lato'
  | 'Slabo27px'
  | 'RobotoCondensed'
  | 'Montserrat'
  | 'SourceSansPro'
  | 'Oswald'
  | 'Raleway'
  | 'Merriweather'
  | 'PTSans'
  | 'NotoSans'
  | 'RobotoSlab'
  | 'PTSerif'
  | 'Poppins'
  | 'Lora'
  | 'Ubuntu'
  | 'DancingScript'
  | 'PlayfairDisplay'
  | 'Arimo'
  | 'TitilliumWeb'
  | 'Nunito'
  | 'NotoSerif'
  | 'Mukta'
  | 'Muli'
  | 'Cabin'
  | 'FiraSans'
  | 'Quicksand'
  | 'Karla'
  | 'Alegreya'
  | 'WorkSans'
  | 'Inconsolata'
  | 'ZillaSlab'
  | 'LibreBaskerville'
  | 'Hind'
  | 'Vollkorn'
  | 'CrimsonText'
  | 'Rubik'
  | 'Archivo'
  | 'OldStandardTT'
  | 'JosefinSans'
  | 'Abel'
  | 'Lobster'
  | 'AmaticSC'
  | 'Pacifico'
  | 'YanoneKaffeesatz'
  | 'Comfortaa'
  | 'CormorantGaramond'
  | 'Spectral'
  | 'Play'
  | 'Barlow'
  | 'EBGaramond'
  | 'Kanit'
  | 'Domine'
  | 'Bitter'
  | 'VarelaRound'
  | 'Assistant'
  | 'Heebo'
  | 'Catamaran'
  | 'ArchivoNarrow'
  | 'SpaceMono'
  | 'PatuaOne'
  | 'Caveat'
  | 'Exo2'
  | 'Prompt'
  | 'Asap'
  | 'NanumGothic'
  | 'LobsterTwo'
  | 'Varela'
  | 'MeriendaOne'
  | 'CreteRound'
  | 'Changa'
  | 'BreeSerif'
  | 'NotoSansKR'
  | 'IndieFlower'
  | 'FjallaOne'
  | 'Acme'
  | 'FredokaOne'
  | 'Teko'
  | 'Cuprum'
  | 'Monda'
  | 'Satisfy'
  | 'Signika'
  | 'GloriaHallelujah'
  | 'BalooBhaijaan'
  | 'Cairo'
  | 'Rokkitt'
  | 'Orbitron'
  | 'Tinos'
  | 'QuattrocentoSans'
  | 'SairaExtraCondensed'
  | 'PassionOne'
  | 'Cinzel'
  | 'Courgette'
  | 'Arvo'
  | 'Cookie'
  | 'Anton'
  | 'FrancoisOne'
  | 'MavenPro'
  | 'GothicA1';
